spring.application.name=gateway
authorization.path=http://172.31.6.9:8081/login/users
chat.path=http://172.31.6.9:8084/chat
buildgenerator.path=http://172.31.6.9:8083/build
comment.path=http://172.31.6.9:8085/comments
post.path=http://172.31.6.9:8085/posts
like.path=http://172.31.6.9:8085/likes
saldotecnico.path=http://172.31.6.9:8082/technicians
server.port=8086
jwt.secret=7Jh6pX3kP9mZ2qR5nV8wL4bT1cY3fM9jN7Kd4vF5hG2sW8xQ9nB5vC6tR4mH8jL3
jwt.expiration=86400000