name: Build Progetto
on: [push]
jobs:
  build-tutto:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4
      
      - name: Prepara Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compila Gateway
        run: mvn -B package --file gateway/pom.xml -DskipTests

      - name: Compila Chat
        run: mvn -B package --file chat/pom.xml -DskipTests
      
      - name: Compila Forum
        run: mvn -B package --file forum/pom.xml -DskipTests
      
      - name: Compila Authorization
        run: mvn -B package --file authorization/pom.xml -DskipTests